DROP TABLE COUPON; 
DROP SEQUENCE COUPONSEQ; 

CREATE SEQUENCE COUPONSEQ;

CREATE TABLE COUPON(
	COUPONSEQ NUMBER PRIMARY KEY,
	COUPONNO VARCHAR2(1000) NOT NULL,
	USERSEQ NUMBER NOT NULL,
	DISCOUNT NUMBER NOT NULL,
	USECHK CHAR(1) DEFAULT 'N' NOT NULL, 
	CPSTART VARCHAR2(1000) NOT NULL,
	CPEND VARCHAR2(1000) NOT NULL, 
	
	CONSTRAINT COUPON_CK CHECK(USECHK IN ('Y','N'))


);