DROP TABLE COUPON; 
DROP SEQUENCE COUPONSEQ; 

DROP TABLE MAKECOUPON; 
DROP SEQUENCE MAKESEQ;



CREATE SEQUENCE COUPONSEQ;
CREATE SEQUENCE MAKESEQ;



--쿠폰 생성 테이블 
CREATE TABLE MAKECOUPON(
	MAKESEQ NUMBER PRIMARY KEY,
	COUPONTITLE VARCHAR2(1000) NOT NULL,
	DISCOUNT NUMBER NOT NULL,
	USERSEQ NUMBER NOT NULL
);

INSERT INTO MAKECOUPON
VALUES(MAKESEQ.NEXTVAL,'PTSD가 쏜다 ! ',10000,1);

SELECT * FROM MAKECOUPON;



--쿠폰 다운로드 테이블

CREATE TABLE COUPON(
	COUPONSEQ NUMBER PRIMARY KEY,
	COUPONNO VARCHAR2(1000) NOT NULL,
	USERSEQ NUMBER NOT NULL,
	DISCOUNT NUMBER NOT NULL,
	USECHK CHAR(1) DEFAULT 'N' NOT NULL, 
	COUPONDATE DATE NOT NULL,
	
	CONSTRAINT COUPON_CK CHECK(USECHK IN ('Y','N'))


);