DROP SEQUENCE PRODUCTLIKESEQ;
DROP TABLE PRODUCTLIKE;

CREATE SEQUENCE PRODUCTLIKESEQ;

CREATE TABLE PRODUCTLIKE (
	LIKESEQ NUMBER PRIMARY KEY,
	PRODUCTSEQ NUMBER NOT NULL,
	USERSEQ NUMBER NOT NULL
);

SELECT LIKESEQ, PRODUCTSEQ, USERSEQ
FROM PRODUCTLIKE;