DROP SEQUENCE REVIEWLIKESEQ;
DROP TABLE REVIEWLIKE;

CREATE SEQUENCE REVIEWLIKESEQ;

CREATE TABLE REVIEWLIKE (
	LIKESEQ NUMBER PRIMARY KEY,
	REVIEWSEQ NUMBER NOT NULL,
	USERSEQ NUMBER NOT NULL
);

SELECT LIKESEQ, REVIEWSEQ, USERSEQ
FROM REIVEWLIKE;