DROP SEQUENCE NOTICESEQ;
DROP TABLE NOTICEBOARD;

CREATE SEQUENCE NOTICESEQ;

CREATE TABLE NOTICEBOARD(
	BOARDSEQ NUMBER PRIMARY KEY,
	BOARDKIND VARCHAR2(200) NOT NULL,
	BOARDNAME VARCHAR2(100) NOT NULL,
	BOARDTITLE VARCHAR2(1000) NOT NULL,
	BOARDCONTENT VARCHAR2(4000) NOT NULL,
	USERSEQ NUMBER NOT NULL,
	BOARDDATE DATE NOT NULL
);


INSERT INTO NOTICEBOARD(BOARDSEQ, BOARDNAME, BOARDTITLE, BOARDCONTENT, USERSEQ, BOARDDATE) SELECT NOTICESEQ.NEXTVAL, BOARDNAME, BOARDTITLE, BOARDCONTENT, USERSEQ, BOARDDATE FROM NOTICEBOARD;

INSERT INTO NOTICEBOARD 
VALUES(NOTICESEQ.NEXTVAL,'NOTICE','차가람','공지글입니다','공지사항 입니다! ', '1000',SYSDATE);

INSERT INTO NOTICEBOARD 
VALUES(NOTICESEQ.NEXTVAL,'EVENT','차가람','이벤트글입니다','이벤트 입니다! ', '1000',SYSDATE);

SELECT * FROM NOTICEBOARD;

