
DROP TABLE RECOMMAND;

DROP SEQUENCE RECOMMANDNOSEQ;

CREATE TABLE RECOMMAND (
	RECOMMANDSEQ NUMBER PRIMARY KEY,
	USERSEQ NUMBER NOT NULL,
	PRODUCTSEQ NUMBER NOT NULL	
);

CREATE SEQUENCE RECOMMANDNOSEQ;

SELECT RECOMMANDSEQ, USERSEQ, PRODUCTSEQ
FROM RECOMMAND;

ALTER TABLE RECOMMAND ADD CONSTRAINT RECOMMAND_USERSEQ_FK FOREIGN KEY(USERSEQ) REFERENCES PTSD_USER(USERSEQ);
ALTER TABLE RECOMMAND ADD CONSTRAINT RECOMMAND_PRODUCTSEQ_FK FOREIGN KEY(PRODUCTSEQ) REFERENCES PRODUCT(PRODUCTSEQ);

