DROP SEQUENCE REVIEWSEQ;
DROP TABLE REVIEW;

CREATE CEQUENCE REVIEWSEQ;

CREATE TABLE REVIEW(
	REVIEWSEQ NUMBER PRIMARY KEY,
	PRODUCTSEQ NUMBEE NOT NULL,
	REVIEWNAME VARCHAR2(200) NOT NULL,
	REVIEWCONTENT VARCHAR2(4000) NOT NULL,
	REVIEWLIKECNT NUMBER DEFAULT 0 NOT NULL,
	REVIEWDATE DATE NOT NULL
);

