DROP SEQUENCE STREAMINGSEQ;
DROP TABLE STREAMING;

CREATE SEQUENCE STREAMINGSEQ;

CREATE TABLE STREAMING(
	STREAMINGSEQ NUMBER PRIMARY KEY,
	STREAMINGNAME VARCHAR2(4000) UNIQUE
);

INSERT INTO STREAMING
VALUES(STREAMINGSEQ.NEXTVAL, '이것저것');

INSERT INTO STREAMING
VALUES(STREAMINGSEQ.NEXTVAL, '방방봐');

INSERT INTO STREAMING
VALUES(STREAMINGSEQ.NEXTVAL, '먹방');

INSERT INTO STREAMING
VALUES(STREAMINGSEQ.NEXTVAL, '치킨');

SELECT STREAMINGSEQ, STREAMINGNAME
FROM STREAMING;
