
DROP TABLE WISHLIKE;

DROP SEQUENCE WISHLIKESEQ;

CREATE TABLE WISHLIKE (
	WISHLIKESEQ NUMBER PRIMARY KEY,
	WISHSEQ NUMBER NOT NULL,
	USERSEQ NUMBER NOT NULL
);

SELECT WISHLIKESEQ, WISHSEQ, USERSEQ
FROM WISHLIKE;
