
DROP TABLE WISHLIKE;

DROP SEQUENCE WISHLIKESEQ;

CREATE TABLE WISHLIKE (
	WISHLIKESEQ NUMBER PRIMARY KEY,
	PRODUCTSEQ NUMBER NOT NULL,
	USERSEQ NUMBER NOT NULL,
	WISHLIKECHECK NUMBER DEFAULT 0
);

CREATE SEQUENCE WISHLIKESEQ;

SELECT WISHLIKESEQ, PRODUCTSEQ, USERSEQ, WISHLIKECHECK
FROM WISHLIKE;

ALTER TABLE WISHLIKE ADD CONSTRAINT WISHLIKE_USERSEQ_FK FOREIGN KEY(USERSEQ) REFERENCES PTSD_USER(USERSEQ);
ALTER TABLE WISHLIKE ADD CONSTRAINT WISHLIKE_PRODUCTSEQ_FK FOREIGN KEY(PRODUCTSEQ) REFERENCES PRODUCT(PRODUCTSEQ);
