DROP TABLE WISH;

DROP SEQUENCE WISHSEQ;
CREATE SEQUENCE WISHSEQ;
CREATE TABLE WISH(
	
	WISHSEQ         NUMBER    PRIMARY KEY,
	PRODUCTSEQ      NUMBER    NOT NULL,
	USERSEQ         NUMBER    NOT NULL
);

SELECT COUNT(*) FROM WISH
WHERE PRODUCTSEQ = #{productseq}
AND USERSEQ = #{userseq}

SELECT PRODUCTSEQ FROM WISH
WHERE USERSEQ = #{userseq}

SELECT COUNT(*) FROM WISH
WHERE PRODUCTSEQ = 해당 상품 숫자



ALTER TABLE WISH ADD CONSTRAINT WISH_USERSEQ_FK FOREIGN KEY(USERSEQ) REFERENCES PTSD_USER(USERSEQ);
ALTER TABLE WISH ADD CONSTRAINT WISH_PRODUCTSEQ_FK FOREIGN KEY(PRODUCTSEQ) REFERENCES PRODUCT(PRODUCTSEQ);

SELECT * FROM PTSD_USER;
SELECT * FROM PRODUCT;

ROLLBACK;

INSERT INTO WISH
VALUES (WISHSEQ.NEXTVAL, 1, 2);

SELECT * FROM WISH;

SELECT U.USERID, P.PRODUCTNAME, P.PRICE
FROM PTSD_USER U, PRODUCT P, WISH W
WHERE U.USERSEQ = W.USERSEQ AND P.PRODUCTSEQ = W.PRODUCTSEQ;

